package com.softsquared.template.kotlin.util

object Constants {

    // 쉐어프리프런스 상수 값
    val USER_NICKNAME = "USER_NICKNAME"
    val USER_ID = "USER_ID"
    val EXPAND = "EXPAND"
    val COLLASPE = "COLLASPE"
    val HIDE_SHEET = "HIDE_SHEET"
    val EDIT_SCHEDULE_ID = "EDIT_SCHEDULE_ID"
    var IS_EDIT = false
    val COMMENTS = "COMMENTS"
    val DAY = "DAY"
    val GOALTITLE = "GOALTITLE"
    val DDAY_CHECK = "DDAY_CHECK"
    val FIND_USER_ID = "FIND_USER_ID"
    val OTP_TOKEN = "OTP_TOKEN"

    val KAKAO_USER_NICKNAME = "KAKAO_USER_NICKNAME"
    val KAKAO_USER_ID = "KAKAO_USER_ID"
    val KAKAO_THUMBNAILIMAGEURL = "KAKAO_THUMBNAILIMAGEURL"
    val KAKAO_JWT = "JWT"
    val KAKAO_EMAIL = "KAKAO_EMAIL"

    val CHECK = "CHECK"
    val DELETE_CHECKED_ITEM = "DELETE_CHECKED_ITEM"
    val DELETE_NOT_CHECKED_ITEM = "DELETE_NOT_CHECKED_ITEM"

    val SEARCHWROD = "SEARCHWROD"
    val SEARCH_WROD_COLOR = "SEARCH_WROD_COLOR"
    val SEARCH_CNT = "SEARCH_CNT"
    var SEARCH_CHECK = true
    var SEARCH_TEST = "SEARCH_TEST"

    val PROFILE_KAMERA = "PROFILE_KAMERA"
    val PROFILE_GALLERY = "PROFILE_GALLERY"

    val DEVICE_WIDTH : Int = 1

    val ID_PASSWORD_CHECH = "ID_PASSWORD_CHECH"
    val BOOKMARK_LATELY_CHECH = "BOOKMARK_LATELY_CHECH"

    val FILTER_LEFT = "FILTER_LEFT"
    val FILTER_DONE = "FILTER_DONE"
    val FILTER_RECENT = "FILTER_RECENT"
    val FILTER_BOOKMARK = "FILTER_BOOKMARK"
    val FILTER_CHECH_NUM = "FILTER_CHECH_NUM"

}